set encoding=utf-8
set hidden


set nobackup
set nowritebackup

set cmdheight=2

set updatetime=300

set shortmess+=c

set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent

"exrc	enable reading .vimrc/.exrc/.gvimrc in the current directory
set exrc


set number
set relativenumber

set nohlsearch

set nowrap

set incsearch
set scrolloff=8

set colorcolumn=80
set signcolumn=yes


let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'gruvbox-community/gruvbox'
Plug 'dense-analysis/ale'
Plug 'mattn/emmet-vim'
Plug 'turbio/bracey.vim'
Plug 'pangloss/vim-javascript'
Plug 'maxmellon/vim-jsx-pretty'
call plug#end()

let g:ale_completion_enabled = 1

colorscheme gruvbox
hi Normal guibg=NONE ctermbg=NONE
