set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent

"exrc	enable reading .vimrc/.exrc/.gvimrc in the current directory
set exrc


set number
set relativenumber

set nohlsearch

set nowrap

set incsearch
set scrolloff=8

set colorcolumn=80
set signcolumn=yes


let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'gruvbox-community/gruvbox'
call plug#end()

colorscheme gruvbox
hi Normal guibg=NONE ctermbg=NONE
